config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'employees#index'
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]
  
  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create 
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save 
        format.html {redirect_to @employee, notice: "Employee Added successfuly"}
      else
        format.html {render :new}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html {redirect_to @employee, notice: "Employee Updated successfuly"}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html {redirect_to employees_path, notice: "Employee Deleted successfuly"}
    end
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :email, :dob)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def find_factor(age)
    factors = []
    (1..age/2).each do|number|
      if age % number == 0
        factors.push(number)
      end
    end
    return factors
  end

  def is_prime(age)
    (2..age/2).each do |number|
      if age % number == 0
        return "Not Prime"
      end
    end
    return "Prime"
  end
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <div class="form-group">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :email, "Email" %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>  
  <div class="form-group">
    <%= form.label :dob, "Date of Birth" %>
    <%= form.date_field :dob, class: 'form-control' %>
  </div>
  <%= form.submit "Submit", class: 'btn btn-primary'%>
<% end %>

app/views/employees/edit.html.erb
<div class="container">
  <h1>Edit Employee</h1>
  <%= render 'form', employee: @employee %>
  <%= link_to 'Back', employees_path %>
</div>

app/views/employees/index.html.erb
<div class="container">
  <div style="display: inline-block;">
    <h1>Employees</h1>  
  </div>
  <div style="display: inline-block; margin-left: 100px;">
    <%= link_to "New Employee", new_employee_path, class: 'btn btn-primary' %>
  </div>
  <table class="container">
    <thead>
      <th> Name </th>
      <th> Email </th>
      <th> Age </th>
      <th> Factors </th>
      <th> Isprime </th>
      <th colspan="3"> Actions </th>
    </thead>
    <% @employees.each do |employee|%>
    <tbody>
      <tr>
        <td> <%= employee.name %> </td>
        <td> <%= employee.email %> </td>
        <% age = ((Time.zone.now - employee.dob.to_time) / 1.year.seconds).floor %>
        <td> <%= age %> </td>
        <td> <%= find_factor(age) %> </td>
        <td> <%= is_prime(age) %> </td>
        <td> <%= link_to "Show", employee %> </td>
        <td> <%= link_to "Edit", edit_employee_path(employee) %> </td>
        <td> <%= link_to "Delete", employee, method: :delete, data: {confirm: 'Are you sure?'} %> </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

<div>
  <a href="#" onclick="paintIt(event, '#990000')">Paint it red</a>
</div>
<div>
  <a href="#" onclick="paintIt(event, '#990000')">Paint it red</a>
  <a href="#" onclick="paintIt(event, '#009900', '#FFFFFF')">Paint it green</a>
  <a href="#" onclick="paintIt(event, '#000099', '#FFFFFF')">Paint it blue</a>
</div>
<div>
  newwww links 
  <a href="#" data-background-color="#990000">Paint it red</a>
  <a href="#" data-background-color="#009900" data-text-color="#FFFFFF">Paint it green</a>
  <a href="#" data-background-color="#000099" data-text-color="#FFFFFF">Paint it blue</a>
</div>

<script type="text/javascript">
  
  function paintIt(element, backgroundColor, textColor) {
  element.style.backgroundColor = backgroundColor;
  if (textColor) {
    element.style.color = textColor;
  }
}

window.addEventListener("load", () => {
  const links = document.querySelectorAll(
    "a[data-background-color]"
  );
  links.forEach((element) => {
    element.addEventListener("click", (event) => {
      event.preventDefault();

      const {backgroundColor, textColor} = element.dataset;
      console.log("backgroundColor is:"+Object.keys(element.dataset)+" and textColor:"+textColor);
      paintIt(element, backgroundColor, textColor);
    });
  });
});

</script>

app/views/employees/new.html.erb
<div class="container">
  <h1>New Employee</h1>
  <%= render 'form', employee: @employee %>
  <%= link_to 'Back', employees_path %>
</div>

app/views/employees/show.html.erb
<br>
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>
<p>
  <strong>Age:</strong>
  <%= ((Time.zone.now - @employee.dob.to_time)/ 1.year.seconds).floor %>
</p>

<%= link_to "Edit", edit_employee_path %>
<%= link_to "Back", employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice" align="center"> <%= notice %></p>
    <%= yield %>
  </body>
</html>